[tool.poetry]
name = "sqlstuff"
version = "0.1.0"
description = ""
authors = ["Brandon"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
sqlite-utils = "^3.37"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
